name: Deploy Application

on:
  push:
    branches:
      - main  # or any branch you want the deployment to trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      # Step 3: Install dependencies
      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    python -m pip install -r requirements.txt

      # Step 4: Deploy the code via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}  # Add the host as a secret in GitHub Actions
          username: ubuntu  # Add the server username as a secret
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add the private SSH key as a secret
          port: 22  # Optional, set this if not using default SSH port
          script: |
            cd /home/ubuntu/vsystech-users-backend/backend || exit 1
           
            bash codeupdate.sh || exit 1 
            
